<?php namespace CIC\Rollbar\Error;

/**
 * Class ExceptionHandler
 * @package CIC\Rollbar\Error
 */
class ErrorHandler extends \t3lib_error_ErrorHandler {
    /**
     * @param int $errorLevel
     * @param string $errorMessage
     * @param string $errorFile
     * @param int $errorLine
     * @return bool
     */
    public function handleError($errorLevel, $errorMessage, $errorFile, $errorLine) {
        parent::handleError($errorLevel, $errorMessage, $errorFile, $errorLine); // TODO: Change the autogenerated stub
        if ($GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['rollbar']['set_error_handler']) {
            \Rollbar::report_php_error($errorLevel, $errorMessage, $errorFile, $errorLine);
        }
    }
}
